In [14]:
#Создать 2 массива NumPy
#Один из случайных чисел, второй - использую arange Или linspace
#Изменить форму массива

In [ ]:
import numpy as np

In [23]:
random_array = np.random.random(10)
random_array = random_array.reshape(2,5)
random_array

array([[0.80953975, 0.7503431 , 0.49621073, 0.11207527, 0.83057202],
       [0.09904679, 0.48522504, 0.42871198, 0.0475287 , 0.43890132]])

In [15]:
arange_array = np.arange(0,10)
arange_array = arange_array.reshape(2,5)
arange_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:

#После этого выполнить математические операции- сложить, перемножить, делить

In [11]:
arange_array + random_array

array([[0.23653768, 1.0406258 , 2.72141888, 3.28029097, 4.32834916],
       [5.28484119, 6.52854214, 7.65023299, 8.96772411, 9.25814576]])

In [12]:
arange_array * random_array

array([[0.        , 0.0406258 , 1.44283775, 0.84087291, 1.31339664],
       [1.42420596, 3.17125285, 4.55163092, 7.7417929 , 2.3233118 ]])

In [13]:
arange_array / random_array

array([[ 0.        , 24.61489827,  2.77231449, 10.70316318, 12.18215388],
       [17.55364088, 11.35198034, 10.76537198,  8.26681892, 34.86402472]])

In [16]:

#Найти максимальный элемент в каждой строчке и столбце первого массива (из случайных чисел_

In [18]:
random_array.max(axis = 0)

array([0.28484119, 0.52854214, 0.72141888, 0.96772411, 0.32834916])

In [19]:
random_array.max(axis = 1)

array([0.72141888, 0.96772411])

In [20]:

#Найти максимальный элемент в из 2 массивов

In [21]:
max(random_array.max(), arange_array.max())

9